### ISSUE TITLE
I can't get it started

### ISSUE THREAD

**Issue by xOxygeny** [Cr4xy/agar-lvlgen#10]
Hi. When i Open "Start" with Admin, i have this.

http://i.imgur.com/CyVdwKw.png

When i write "npm install ws", i have this.

http://i.imgur.com/l282x2u.png

Can u help me fast?

**Comment by ghost** [comment]
You get it because your lvlgen.js is not in Windows/system32. I hope start.bat gets fixed ASAP, but you can install it via terminal:
1. Type `cd` and drag'n'drop the folder where start.bat is to terminal
2. If the command is `cd <path to your agar-lvlgen-master folder>` run it to set folder
3. Type `node lvlgen`

**Comment by xOxygeny** [comment]
It's Ok, but when bots are spawning, in agario my lvl its the same.....
For me this dont work. I copy all from facebook cookies, and didnt work :c

**Comment by xOxygeny** [comment]
{ connected: 16,
  spawned: 16,
  totalScore: 395,
  avgScore: 25,
  highest: 104 }
{ connected: 16,
  spawned: 16,
  totalScore: 400,
  avgScore: 25,
  highest: 104 }

Maybe it is ok, but in agario my level and XP it is the same. Can u help me?

**Comment by hassanila** [comment]
Agar.io just patched it... it wont work sry.

**Comment by makandz** [comment]
@eroo123451 To make it work, you can only run one process. Change the amount of bots to 1 and make sure not to be logged into Facebook if you are. (Because the new update only allows login to Facebook ones for _all_ servers.)
