### ISSUE TITLE
how to get new update?????

### ISSUE THREAD

**Issue by yoyo00x** [Cr4xy/agar-lvlgen#11]
i downloaded the new update but it lookes the same and it gives a max of 30 bots only

**Comment by ghost** [comment]
It is almost same, only Start.command changed. Nothing more, nothing less. Remember to [watch the commit log](https://github.com/Cr4xy/agar-lvlgen/commits/master), it's made for you and tells what is updated.

And because nothing more than one file changed, your issue isn't lvlgen's fault. Agar.io was yesterday about hour in maintentance mode, and I think they tried to fix this during it. But I really, really hope that someone can fix issues with their blocker - and I'm pretty sure it's possible, because I've seen people with other bots in the game.
