### ISSUE TITLE
New Revision

### ISSUE THREAD

**Issue by ncmp** [Cr4xy/agar-lvlgen#28]
With the new revision I only get 1 bot connected whereas with the older one i had like 175 bots connected constantly. What could be the reason?

**Comment by clairekardas** [comment]
Agar patch, read README.md. "It seems like agar.io now patched the ability that you can log in with a facebook account multiple times, sorry everybody"

**Comment by Cr4xy** [comment]
174 bots had no FB. It maybe looked cool but was useless. ;)

**Comment by ncmp** [comment]
Oh is that the case? I thought the bots recognized each other and fed each other so it could have had effect. But that's an idea is it not? What if we make those 175 bots recognize each other so they feed the one that has FB. In that case, we'll get more exp, no?

**Comment by hassanila** [comment]
YES!  @suxosuxo123 GOOD IDEA...   :+1:

**Comment by clairekardas** [comment]
But with the anti bot update isnt it impossible that the bots go where you want them? @Cr4xy

**Comment by hassanila** [comment]
It's actually possible to get mouse control and coords just like before (some people here have it) but they won't share   the only thing we can do now is to set the bots to blind mode

**Comment by makandz** [comment]
@hassanila97 Actually that's not how blind mode works. A bot would run around the map for a couple seconds, once it has come into the radius of the main player then it would go into that player following the player_id. People have implemented mouse control but I have no idea how to do this.

This was possible in Feeder-Bot but it looks as if Agar.io patched it or support was just dropped, because one of the variables isn't found in the agarioclient anymore.
