### ISSUE TITLE
Bot Split

### ISSUE THREAD

**Issue by NoorAgario** [Cr4xy/agar-lvlgen#69]
Can we see our bot while playing ? , Can the bot split or it just move and eat small food cuz it mine just reached 3800 and if it don't split it wont probably gain any more mass

**Comment by NoorAgario** [comment]
and then the game reseted ****

**Comment by NoorAgario** [comment]
@MastaCoder  @Cr4xy

**Comment by makandz** [comment]
@NoorAgario Right now you can't view the bot playing because of CPU and keeping this program lightweight. About the bot getting mass, it most likely will be getting mass. It just won't be getting it from food or splitting for it :)

The game shouldn't reset in the latest update. It only resets if the bot dies.

**Comment by NoorAgario** [comment]
Help it reached 1200 again and it reset :/ I don't know what is happing with my bot its getting rly large but it keeps resetting

**Comment by NoorAgario** [comment]
aww I haven't updated
