### ISSUE TITLE
I get logout from my account

### ISSUE THREAD

**Issue by dawitrange** [Cr4xy/agar-lvlgen#8]
I dont like how you added that you log out of your account whats so good about that you lvl up faster or is it a bug?

**Comment by ghost** [comment]
Again, let's repeat - **it is not  LVLGEN's fault**, it's a fix made by Moneyclip to calm botters down. I, and many others, hope that is gets fixed soon, the fix was terrible for level gen's functionality. 

People want to gain levels fast for possibilities. They want more skins and levels faster - and of course also coins!

**Comment by hassanila** [comment]
Idk if it will be fixed anytime soon.   As it's useless to code it, share it, then MONEYCLIP takes it down...   Doesn't sound logic.... so I think that no coder will share the code.

**Comment by caveman1973** [comment]
I can't login to my account anymore. Guess AGARIO is banning bots.

**Comment by david12344** [comment]
omg dude when is this bug fixed or lvl gen master not working omg i am lvl 85 and i want to be lvl 100 so pls fixed this bug

**Comment by hassanila** [comment]
This cant theoretically be fixed... as it is from server side... so no hope

**Comment by hassanila** [comment]
But you can have 1 bot play for you with multiple fb accs.
